name: Dad Joke
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  dadjoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: abhisheknaiidu/dad-jokes@master
