name: Metrics (Fast Test)

on:
  workflow_dispatch:  # run manually only

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metrics (Fast)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          template: classic
          config_timezone: Asia/Kolkata
          plugin_languages: yes
          theme: dark
