name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # runs every day at midnight UTC
  workflow_dispatch:     # allows manual trigger

permissions:
  contents: write        # needed to push to the output branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: whopie29
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake-neon.svg?color_snake=%2339FF14

      - name: Push generated files to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B output
          git add dist
          git commit -m "Generated snake animation" || echo "No changes to commit"
          git push origin output --force
